# Generated by Django 3.1.7 on 2021-03-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('alias', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
    ]
