# Generated by Django 3.1.7 on 2021-03-24 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0004_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Store',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('name_product', models.CharField(max_length=50)),
                ('mark', models.CharField(max_length=30)),
                ('price', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=256)),
                ('image', models.CharField(max_length=256)),
                ('id_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_id', to='compare.store')),
                ('name_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Category_name', to='compare.category')),
            ],
        ),
    ]
