# Generated by Django 3.1.7 on 2021-03-24 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0005_product_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_store',
            name='name_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_name', to='compare.category'),
        ),
    ]
