# Generated by Django 3.1.7 on 2021-03-24 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0006_auto_20210324_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='store_name', serialize=False, to='compare.product_store', unique=True)),
                ('mark', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=256)),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_product', to='compare.product_store')),
                ('name_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='compare.category')),
            ],
        ),
    ]
