# Generated by Django 3.1.7 on 2021-03-24 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0009_auto_20210324_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='product_name', serialize=False, to='compare.product_store'),
        ),
    ]
