# Generated by Django 3.1.7 on 2021-03-24 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0011_auto_20210324_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name_product',
            new_name='product',
        ),
    ]
