# Generated by Django 3.1.7 on 2021-03-24 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0012_auto_20210324_1601'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
