# Generated by Django 3.1.7 on 2021-04-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compare', '0015_wish_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Labial', 'Labial'), ('Sombras', 'Sombras'), ('Rubor', 'Rubor'), ('Bases', 'Bases'), ('Delineador', 'Delineador'), ('Iluminador', 'Iluminador'), ('Corrector', 'Corrector')], max_length=20),
        ),
    ]
